version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    volumes:
       - db_data:/var/lib/postgresql/data  #数据持久化
  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/yourdb
      SPRING_DATASOURCE_USERNAME: youruser
      SPRING_DATASOURCE_PASSWORD: yourpassword
    #ports:
    # - "8080:8080" # 如果需要暴露Spring Boot应用的端口
    #command: ["./wait-for-it.sh", "db:5432", "--", "java", "-jar", "app.jar"] # 等待数据库启动

volumes:
   db_data: